#!/usr/bin/env bash
# 0028 · THE PRIVATE BUCKET, PROVED WITH REAL HTTP.
#
# Reading a policy tells you what somebody intended. This makes the requests an outsider would make
# and reads the status codes back. It is the only kind of proof that means anything here, because
# `product-images` has a policy `for select to public` and looks almost identical in the catalogue.
#
# Both directions, per rule: an identity that SHOULD be able to read a photograph, and three that
# should not. A bucket that refuses everybody would pass the refusal half perfectly.
#
#   1  anonymous, no key at all            → refused
#   2  anonymous, holding the PUBLISHABLE key (which ships in the page source) → refused
#   3  the public-object URL, guessed      → refused
#   4  a staff account with neither key    → refused (upload AND signing)
#   5  the operator, who holds both        → uploads, signs, and the signed URL returns the bytes
#   6  the same signed URL after it expires → refused
#
# Credentials come from .env and are never printed. Leaves one test object behind, removed at the
# end through psql because 0028 deliberately grants DELETE to nobody (rule 12).
set -u
set -a && . ./.env && set +a

URL="$SUPABASE_URL"; PK="$SUPABASE_PUBLISHABLE_KEY"
KEY="probe/0028-$(date +%s).png"
PASS=0; FAIL=0
say() { printf '%-58s %s\n' "$1" "$2"; }
ok()   { PASS=$((PASS+1)); say "$1" "OK    ($2)"; }
bad()  { FAIL=$((FAIL+1)); say "$1" "FAIL  ($2)"; }
# expect <label> <expected-description> <predicate-result 0/1> <actual>
want() { if [ "$3" = "1" ]; then ok "$1" "$4"; else bad "$1" "expected $2, got $4"; fi; }

# A one pixel PNG, so nothing on this machine is uploaded by accident.
PNG=$(mktemp /tmp/0028XXXX.png)
printf '\x89PNG\r\n\x1a\n\x00\x00\x00\rIHDR\x00\x00\x00\x01\x00\x00\x00\x01\x08\x06\x00\x00\x00\x1f\x15\xc4\x89\x00\x00\x00\nIDATx\x9cc\x00\x01\x00\x00\x05\x00\x01\r\n\x2d\xb4\x00\x00\x00\x00IEND\xaeB\x60\x82' > "$PNG"

login() { # $1 email $2 password -> access token on stdout
  curl -s -X POST "$URL/auth/v1/token?grant_type=password" \
    -H "apikey: $PK" -H 'content-type: application/json' \
    -d "$(printf '{"email":%s,"password":%s}' "$(printf '%s' "$1" | python3 -c 'import json,sys;print(json.dumps(sys.stdin.read()))')" "$(printf '%s' "$2" | python3 -c 'import json,sys;print(json.dumps(sys.stdin.read()))')")" \
  | python3 -c 'import json,sys; print(json.load(sys.stdin).get("access_token",""))'
}

echo "── 0028 return-photos ────────────────────────────────────────────────────"

TOKEN=$(login "$OPERATOR_EMAIL" "$OPERATOR_PASSWORD")
[ -n "$TOKEN" ] || { echo "Could not sign in as the operator. Nothing below would mean anything."; exit 1; }

# ---- 5a · THE CONTROL, FIRST. Put a real object there to try to steal. --------------------------
code=$(curl -s -o /dev/null -w '%{http_code}' -X POST "$URL/storage/v1/object/return-photos/$KEY" \
  -H "apikey: $PK" -H "authorization: Bearer $TOKEN" -H 'content-type: image/png' \
  --data-binary "@$PNG")
want "operator uploads (returns.write)" "200/201" "$([ "$code" = 200 ] || [ "$code" = 201 ] && echo 1 || echo 0)" "$code"
[ "$code" = 200 ] || [ "$code" = 201 ] || { echo "No object to attack. Stopping."; rm -f "$PNG"; exit 1; }

# ---- 1 · No key at all --------------------------------------------------------------------------
code=$(curl -s -o /dev/null -w '%{http_code}' "$URL/storage/v1/object/return-photos/$KEY")
want "anonymous, no key" "401/400/404" "$([ "$code" != 200 ] && echo 1 || echo 0)" "$code"

# ---- 2 · The publishable key, which is public by design and ships in the page source -------------
code=$(curl -s -o /dev/null -w '%{http_code}' "$URL/storage/v1/object/return-photos/$KEY" -H "apikey: $PK")
want "anonymous, holding the publishable key" "400/404" "$([ "$code" != 200 ] && echo 1 || echo 0)" "$code"

# ---- 3 · The public-object URL, the shape that works for product-images ---------------------------
code=$(curl -s -o /dev/null -w '%{http_code}' "$URL/storage/v1/object/public/return-photos/$KEY")
want "guessed public URL" "400/404" "$([ "$code" != 200 ] && echo 1 || echo 0)" "$code"

# ---- 4 · A SIGNED-IN ACCOUNT WITH NEITHER KEY ----------------------------------------------------
#
# The arm that proves the two permissions are what decide, rather than merely that the bucket is
# private. Without it the probe shows only "outsiders are refused", which a bucket with no policies
# at all would also show. The identity is built here and destroyed at the end; its password is
# generated by the shell, never stored and never printed.
STAFF_EMAIL="probe-0028-$(date +%s)@example.invalid"
STAFF_PW=$(head -c 18 /dev/urandom | base64 | tr -d '/+=')
psql_q() { PGPASSWORD="$DB_PASSWORD" psql "host=aws-0-ap-south-1.pooler.supabase.com port=5432 dbname=postgres user=postgres.hjidocpqcrfbjucvqggu sslmode=require" -q -v ON_ERROR_STOP=1 "$@"; }
# GoTrue reads more of auth.users than the columns a row strictly needs: the four token columns must
# be '' rather than null, and there must be an auth.identities row, or the password grant answers
# 500 "Database error querying schema" — and this arm degrades into a skip that looks like a pass.
psql_q -c "
  with u as (
    insert into auth.users (id, instance_id, aud, role, email, encrypted_password,
                            email_confirmed_at, created_at, updated_at,
                            raw_app_meta_data, raw_user_meta_data,
                            confirmation_token, email_change, email_change_token_new, recovery_token)
    values (gen_random_uuid(), '00000000-0000-0000-0000-000000000000', 'authenticated', 'authenticated',
            '$STAFF_EMAIL', extensions.crypt('$STAFF_PW', extensions.gen_salt('bf')),
            now(), now(), now(),
            '{\"provider\":\"email\",\"providers\":[\"email\"]}'::jsonb, '{}'::jsonb, '', '', '', '')
    returning id)
  insert into auth.identities (id, user_id, identity_data, provider, provider_id,
                               last_sign_in_at, created_at, updated_at)
  select gen_random_uuid(), u.id, jsonb_build_object('sub', u.id::text, 'email', '$STAFF_EMAIL'),
         'email', '$STAFF_EMAIL', now(), now(), now() from u;" >/dev/null 2>&1
# Deliberately holds ORDERS.WRITE and nothing else: a real job in this business, and one that has no
# business opening a photograph of somebody's damaged cabinet.
psql_q -c "
  select fn_admin_set_operator(
    (select id from auth.users where email = '$STAFF_EMAIL'),
    'Probe 0028', '{\"orders.write\": true}'::jsonb, true);
" >/dev/null 2>&1

STAFF=$(login "$STAFF_EMAIL" "$STAFF_PW")
if [ -n "$STAFF" ]; then
  code=$(curl -s -o /dev/null -w '%{http_code}' "$URL/storage/v1/object/return-photos/$KEY" \
    -H "apikey: $PK" -H "authorization: Bearer $STAFF")
  want "signed in, no returns.write / ledger.view" "400/404" "$([ "$code" != 200 ] && echo 1 || echo 0)" "$code"
  code=$(curl -s -o /dev/null -w '%{http_code}' -X POST "$URL/storage/v1/object/sign/return-photos/$KEY" \
    -H "apikey: $PK" -H "authorization: Bearer $STAFF" -H 'content-type: application/json' -d '{"expiresIn":60}')
  want "  …and cannot mint a signed URL" "400/404" "$([ "$code" != 200 ] && echo 1 || echo 0)" "$code"
  code=$(curl -s -o /dev/null -w '%{http_code}' -X POST "$URL/storage/v1/object/return-photos/probe/steal.png" \
    -H "apikey: $PK" -H "authorization: Bearer $STAFF" -H 'content-type: image/png' --data-binary "@$PNG")
  want "  …and cannot upload evidence of its own" "400/403" "$([ "$code" != 200 ] && [ "$code" != 201 ] && echo 1 || echo 0)" "$code"
  # CONTROL FOR THIS ARM: the same account is a working account, not a broken one. If it were
  # refused everywhere, the three refusals above would prove nothing about the two keys.
  code=$(curl -s -o /dev/null -w '%{http_code}' "$URL/rest/v1/rental_order?select=id&limit=1" \
    -H "apikey: $PK" -H "authorization: Bearer $STAFF")
  want "  …but the same account CAN read orders" "200" "$([ "$code" = 200 ] && echo 1 || echo 0)" "$code"
else
  bad "signed in, neither key" "could not sign the throwaway identity in"
fi

# ---- 5b · The operator reads it back --------------------------------------------------------------
code=$(curl -s -o /dev/null -w '%{http_code}' "$URL/storage/v1/object/return-photos/$KEY" \
  -H "apikey: $PK" -H "authorization: Bearer $TOKEN")
want "operator reads the object" "200" "$([ "$code" = 200 ] && echo 1 || echo 0)" "$code"

SIGNED=$(curl -s -X POST "$URL/storage/v1/object/sign/return-photos/$KEY" \
  -H "apikey: $PK" -H "authorization: Bearer $TOKEN" -H 'content-type: application/json' -d '{"expiresIn":2}' \
  | python3 -c 'import json,sys; print(json.load(sys.stdin).get("signedURL",""))')
want "operator mints a signed URL" "a URL" "$([ -n "$SIGNED" ] && echo 1 || echo 0)" "$([ -n "$SIGNED" ] && echo "got one" || echo "empty")"

if [ -n "$SIGNED" ]; then
  code=$(curl -s -o /dev/null -w '%{http_code}' "$URL/storage/v1$SIGNED")
  want "  …and it serves the bytes with NO key" "200" "$([ "$code" = 200 ] && echo 1 || echo 0)" "$code"
  # ---- 6 · The signed URL is a lease, not a giveaway ---------------------------------------------
  sleep 4
  code=$(curl -s -o /dev/null -w '%{http_code}' "$URL/storage/v1$SIGNED")
  want "  …and stops working when it expires" "400" "$([ "$code" != 200 ] && echo 1 || echo 0)" "$code"
fi

rm -f "$PNG"
# Clean up: the test object (0028 grants DELETE to nobody, rule 12, so this goes through psql) and
# the throwaway identity, operator row first because auth.users is its foreign key.
# THE LAST ARM, WHICH IS ALSO THE CLEANUP. Nothing references this key, so 0028's "draft, not yet
# evidence" policy must let the operator remove it — through the Storage API, because
# storage.protect_delete() refuses a direct DELETE on storage.objects whoever you are.
# The other half of this pair — an ATTACHED photo cannot be removed — needs a movement row pointing
# at a real key, so it is driven on the return screen instead of faked here.
code=$(curl -s -o /dev/null -w '%{http_code}' -X DELETE "$URL/storage/v1/object/return-photos/$KEY" \
  -H "apikey: $PK" -H "authorization: Bearer $TOKEN")
want "operator removes a photo NOT yet on a movement" "200" "$([ "$code" = 200 ] && echo 1 || echo 0)" "$code"
left=$(psql_q -At -c "select count(*) from storage.objects where bucket_id='return-photos' and name like 'probe/%';" 2>/dev/null)
want "  …and the bucket is left as it was found" "0 probe objects" "$([ "$left" = 0 ] && echo 1 || echo 0)" "${left:-?} left"
psql_q -c "delete from operator where user_id in (select id from auth.users where email = '$STAFF_EMAIL');
           delete from auth.identities where provider_id = '$STAFF_EMAIL';
           delete from auth.users where email = '$STAFF_EMAIL';" >/dev/null 2>&1

echo "──────────────────────────────────────────────────────────────────────────"
echo "$PASS passed, $FAIL failed"
[ "$FAIL" = 0 ] || exit 1
