-- 0022_write_idempotency.sql
-- Tapping twice must not send the gear twice.
--
-- The failure is ordinary and this app makes it likelier than most. Chachu taps "Send these out"
-- at a van, nothing visibly happens for a second on a bad link, so he taps again — and two
-- identical dispatch movements land. Six pieces are now recorded as having gone out twelve times,
-- v_order_outstanding says twice what is at the customer, and nothing can be deleted to fix it
-- (rule 12); it takes six corrections and 0019 did not exist until last week.
--
-- THE OFFLINE QUEUE MAKES IT WORSE, not better. A queued write is replayed on reconnect, and a
-- replay that partially succeeded — rows inserted, response lost — is indistinguishable from one
-- that failed. db.js retries oldest-first and stops at the first failure, which is right, but
-- "did this already land?" is a question only the database can answer.
--
-- Maitri answers it with a request_id on every write. Same shape here: the CLIENT generates the id
-- once, when the operator taps, and it travels with the payload — including into IndexedDB, so a
-- replay after a browser restart carries the SAME id as the attempt that may already have landed.
-- A unique index turns the second arrival into a no-op rather than a duplicate.

alter table movement
  add column if not exists request_id uuid;

-- Partial, so the 49 rows already there — and any future write that predates a screen being
-- updated — do not all collide on NULL.
create unique index if not exists uq_movement_request
  on movement (request_id) where request_id is not null;

comment on column movement.request_id is
  'One id per tap, generated by the client before the write and carried through the offline queue unchanged. A replay of a write that already landed collides on uq_movement_request and is refused, which is the correct outcome: the movement exists. Never generate this server-side and never regenerate it on retry — a fresh id on every attempt is exactly the duplicate this column exists to stop.';

-- A batch is one tap. Six pieces going out together share one request_id, so re-sending the batch
-- collides on the first row and the whole INSERT rolls back — all six or none, which is what the
-- operator meant. Per-row ids would let a partial replay through.
