-- 0024_request_seq.sql
-- 0022's unique index made a batch collide with itself.
--
-- The idea was right and the shape was wrong. 0022 put ONE request_id on every movement in a tap
-- and a UNIQUE index on that column — so sending two pieces together produced two rows carrying
-- the same id, and the second one violated the index inside its own INSERT. The whole batch rolled
-- back and the operator was told "This was already sent", which was true of nothing at all.
--
-- It survived the migration's own probe because that probe inserted ONE row per statement. It was
-- found by tapping "Send these out" twice on a real two-piece job and reading the row count:
-- 0 dispatch rows, and a toast claiming a duplicate. 0022's own comment asserts the opposite
-- behaviour in as many words, which is what an unexercised assumption looks like when it is
-- written down confidently.
--
-- THE FIX. Uniqueness is per ROW within a tap, not per tap: (request_id, request_seq). The client
-- numbers the rows in the batch 0..n-1. A replay presents the same pairs, every row collides, and
-- the INSERT rolls back whole — which is still all-or-nothing, and is what the operator meant by
-- one tap. A first send has no collision because those pairs have never been seen.

alter table movement
  add column if not exists request_seq int not null default 0;

drop index if exists uq_movement_request;

create unique index if not exists uq_movement_request
  on movement (request_id, request_seq) where request_id is not null;

comment on column movement.request_seq is
  'Position of this row within its tap, 0-based. Uniqueness is (request_id, request_seq): one tap writes several movements and they must not collide with each other, only with a replay of themselves. Set by the client alongside request_id; never generated server-side.';

comment on column movement.request_id is
  'One id per tap, generated by the client before the write and carried through the offline queue unchanged. With request_seq it makes a replay of a tap collide row for row, so the INSERT rolls back whole rather than writing the movements twice. Never regenerate it on retry — a fresh id on every attempt is exactly the duplicate this exists to stop.';
